/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Queries_graficas;
import Queries_graficas.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author biosh
 */
public class Consulta_directores extends javax.swing.JFrame {

    /**
     * Creates new form Consulta_directores
     */
    public Consulta_directores() {
        initComponents();
        setAlwaysOnTop(true);
        setLocation(400, 240);
        llena_tabla_de_directores_automatico ();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        button2 = new java.awt.Button();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai Light", 3, 18)); // NOI18N
        jLabel1.setText("Consulta directores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 254, 28));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id de director", "Nombre de director", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(70);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(2).setMinWidth(70);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 550, 160));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 380, 30));

        jButton1.setText("Mostrar directores inactivos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        button2.setLabel("SALIR DE QUERY");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 110, -1));

        jButton3.setText("Setear tabla ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, -1));

        jButton4.setText("Ordenar por orden alfabetico ");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jButton5.setText("Ordenar por ID");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //exec usp_muestra_inactivos
         DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
        try{
            String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
                String query ="exec usp_muestra_inactivos";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getInt(1));
             v.add(rs.getString(2));
             v.add(rs.getInt(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        llena_tabla_de_directores_automatico();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
//    Decide_si_ascentente_alfabetico decision = new Decide_si_ascentente_alfabetico();
    Decide_si_descendente_alfabetico decision = new Decide_si_descendente_alfabetico();
    
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        // decision.setVisible(true);
        decision.setVisible(true);
        
        if (decision.getDecide_ascendente()==1) {
            DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            try{
            String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
                String query ="exec usp_ordena_por_orden_alfabetico_asc";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getInt(1));
             v.add(rs.getString(2));
             v.add(rs.getInt(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else if (decision.getDecide_descentente()==1) {
            //exec usp_ordena_por_ID_desc
            DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            try{
            String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
                String query ="exec usp_ordena_por_orden_alfabetico_desc";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getInt(1));
             v.add(rs.getString(2));
             v.add(rs.getInt(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_jButton4MouseClicked
    Decide_si_descendente_id decision_2 =new Decide_si_descendente_id();
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        decision_2.setVisible(true);
        
        if (decision_2.getDecide_ascendente()==1) {
            DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            try{
            String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
                String query ="exec usp_ordena_por_ID_asc";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getInt(1));
             v.add(rs.getString(2));
             v.add(rs.getInt(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else if (decision_2.getDecide_descentente()==1) {
            //exec usp_ordena_por_ID_desc
            DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);
            try{
            String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
                String query ="exec usp_ordena_por_ID_desc";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getInt(1));
             v.add(rs.getString(2));
             v.add(rs.getInt(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
            try{
        String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
        String query ="exec usp_para_consulta_directores_ingresa_directores_a_tabla_2 @nombre_director='"+
                jTextField1.getText()+"'";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getInt(1));
             v.add(rs.getString(2));
             v.add(rs.getInt(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
        
        
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta_directores().setVisible(true);
            }
        });
    }
        public void llena_tabla_de_directores_automatico (){
        DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
            try{
        String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
        String query ="exec usp_para_consulta_directores_ingresa_directores_a_tabla";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getString(1));
             v.add(rs.getString(2));
             v.add(rs.getInt(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
