/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Queries_graficas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author biosh
 */
public class Peliculas_consulta_directores extends javax.swing.JFrame {

    /**
     * Creates new form Peliculas_consulta
     */
    public Peliculas_consulta_directores() {
        setBounds(410,200,750,195); 
        initComponents();
        setResizable(false);
        setAlwaysOnTop(true);
        llena_tabla_de_directores_automatico ();
                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        button1 = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        button2 = new java.awt.Button();

        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Engravers MT", 3, 12)); // NOI18N
        label1.setText("CONSULTA DE PELICULAS POR DIRECTOR");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 370, 30));

        button1.setLabel("SETEAR TABLA DE DIRECTORES");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Director", "Titlulo original", "Titulo de exhibicion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 540, 150));

        jLabel1.setFont(new java.awt.Font("Dubai Light", 3, 14)); // NOI18N
        jLabel1.setText(" Peliculas del director seleccionado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 240, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre de director"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 490, 130));

        button2.setLabel("SALIR DE QUERY");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        llena_tabla_de_directores_automatico();
    }//GEN-LAST:event_button1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    public void llena_tabla_de_directores_automatico (){
        DefaultTableModel modelo =(DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
            try{
        String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
        String query ="exec ingresa_directores_a_tabla_peliculas_por_directores";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getString(1));
             modelo.addRow(v);
             jTable2.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }
    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
                DefaultTableModel modelo =(DefaultTableModel) jTable2.getModel();
        modelo.setRowCount(0);
            try{
        String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
           
                Connection con = DriverManager.getConnection(conexionUrl);
                
                
        String query ="exec usp_busqueda_actualiza_director @nombre_director='"+jTextField1.getText()+"'";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){    
             Vector v = new Vector();
             v.add(rs.getString(1));
             modelo.addRow(v);
             jTable2.setModel(modelo);
        }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        //String query ="exec spu_busqueda_por_director @director = '"+jTable2.getSelectedRow().toString()+"'";
        DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        try{
        String conexionUrl= "jdbc:sqlserver://LAPTOP-V0J5NPNQ\\MSSQLSERVER01:1433;"
                    + "database=Proyecto;"
                    + "user=conexion;"
                    + "password=Proyecto_Bases:);"
                    + "loginTimeout=30";
                Connection con = DriverManager.getConnection(conexionUrl);
                int seleccionar = jTable2.rowAtPoint(evt.getPoint());
                ///System.out.println(String.valueOf(jTable2.getValueAt(seleccionar, 0)) );
        String query ="exec spu_busqueda_por_director @director = '"+String.valueOf(jTable2.getValueAt(seleccionar, 0))+"'";
        PreparedStatement pst = con.prepareStatement(query);
        pst.executeQuery();
        ResultSet rs =pst.executeQuery();
        while(rs.next()){
            Vector v = new Vector();
             v.add(rs.getString(1));
             v.add(rs.getString(2));
             v.add(rs.getString(3));
             modelo.addRow(v);
             jTable1.setModel(modelo);
        }    
          //jTextArea1.setText(jTextArea1.getText()+"\n"+rs.getString(1)+"  "+rs.getString(2)+"  "+rs.getString(3)+"  ");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peliculas_consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peliculas_consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peliculas_consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peliculas_consulta_directores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //new Peliculas_consulta().setVisible(true);
                new Peliculas_consulta_directores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
