/*
he * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_bases_de_datos;

import com.sun.glass.events.KeyEvent;
import com.sun.javafx.scene.traversal.Algorithm;
import Queries_graficas.*;
import java.util.Timer;
import java.util.TimerTask;
import java.applet.AudioClip;
import java.awt.Toolkit;
import java.awt.*;
import java.util.Arrays;
import java.awt.event.*;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Random;
import java.io.*;
import sun.audio.*;
import java.util.concurrent.ScheduledExecutorService;
import java.lang.Thread;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sun.util.calendar.CalendarUtils;

/**
 *
 * @author biosh
 */
public class Realiza_programa extends javax.swing.JFrame {
        private boolean variable_se_aplica_heapify=false,variable_app=false;
        private int variable_comprueba_vaciado =0,variable_se_ingresan_datos_despues_de_vaciado=0;
        private  String raiz_de_cbt =new String();
        private String Para_imprimir =new String();
        private boolean se_ha_modificado_array=false;

        private ArrayList<Integer> Complete_binary_tree_array= new ArrayList<>();
        private ArrayList<Integer> auxiliar= new ArrayList<>();
        private String obtiene_matriz=new String();
        private int contador_para_agregar=0,contador_para_auxiliar=0;
        private int[] mostrar= new int[0];
        private boolean on_off_arbol_cbt=false;

    //public Example2 nuev=new Example2();
    /**
     * @return the char_aborrar
     */
    public char getChar_aborrar() {
        return char_aborrar;
    }

    /**
     * @param char_aborrar the char_aborrar to set
     */
    public void setChar_aborrar(char char_aborrar) 
    {
        this.char_aborrar = char_aborrar;
    }
      public ArrayList<Character> para_transmitir= new ArrayList<>(); 
      public ArrayList<Character> lista_2= new ArrayList<>();
     private int tamanio_array=0,contador_para_modificacion=0;
    private int ingreso_a_dinamic_array=0,numero_para_la_matriz=0,index_de_agregacion=0;
     private char char_aborrar=0;
     private String cadena_en_text_field= new String();
     private String muestra_los_dos_heaps= new String();
     /**
     * Creates new form HACE_PROGRAMA
     */
       public AudioClip sonido_click ;
  
    public Realiza_programa()
    {
      //  this.Algorithm = new Heap_sort();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Engravers MT", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heap_sort/imagenes/instrucciones_bien.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 650, 0));

        button1.setBackground(new java.awt.Color(153, 153, 153));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        button1.setLabel("SALIR");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heap_sort/imagenes/fondo_para_realiza_programa_2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        jMenuBar1.setForeground(new java.awt.Color(51, 255, 51));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(120, 32769));

        jMenu1.setText("Peliculas");
        jMenu1.setFont(new java.awt.Font("DialogInput", 2, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem1.setText("Consulta de peliculas por director");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem2.setText("Agregar pelicula");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem6.setText("Eliminar pelicula");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem3.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem3.setText("Consultar pelicula por año");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem7.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem7.setText("Consultar pelicula por año y pais");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Directores");
        jMenu3.setFont(new java.awt.Font("DialogInput", 2, 24)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem4.setText("Consultar directores ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem5.setText("Registra y desactiva directores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Paises");
        jMenu2.setFont(new java.awt.Font("DialogInput", 2, 24)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Dubai", 3, 14)); // NOI18N
        jMenuItem8.setText("Agregar paises");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed
        Peliculas_consulta_directores Hace_consulta = new Peliculas_consulta_directores();
        peliculas_consulta_anio Hace_consulta_anio = new peliculas_consulta_anio();        
        Consulta_directores Hace_consulta_directores = new Consulta_directores();
        busca_por_pais_anio busqueda_pais_anio = new busca_por_pais_anio();
        agrega_director agregamos_director = new agrega_director();
        Agrega_pelicula Nueva_pelicula = new Agrega_pelicula();
        Decide_si_por_director_o_titulo decision = new Decide_si_por_director_o_titulo();
        Agregar_paises agrega_paises= new Agregar_paises();
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Hace_consulta.setVisible(true);
        /*agregar metodo que muestre los directores de forma alfabetica*/
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Nueva_pelicula.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Hace_consulta_anio.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Hace_consulta_directores.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        busqueda_pais_anio.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        agregamos_director.setVisible(true);
        agregamos_director.muestra_automatico_id_recomendado();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        decision.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        agrega_paises.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed
     
    /**
     * @param args the command line arguments
     */
      public static  Realiza_programa application_2 =new Realiza_programa();
   
 public static void main(String args[]) 
 {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                application_2.setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables

    
}
